# Generated by Django 5.0.7 on 2024-07-21 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chilestay', '0005_inmueble_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='tipo_inmueble',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chilestay.tipoinmueble'),
        ),
    ]
