# Generated by Django 5.0.7 on 2024-07-21 17:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chilestay', '0003_usuario_correo_electronico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='calificacion_sernatur',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='correo_electronico',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='descripcion',
            field=models.TextField(default='Descripción por defecto'),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='pagina_web',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='servicios',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='tipo_inmueble',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='usuarios',
            field=models.ManyToManyField(related_name='inmuebles', to=settings.AUTH_USER_MODEL),
        ),
    ]
