# Generated by Django 5.0.7 on 2024-07-21 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chilestay', '0004_inmueble_calificacion_sernatur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='direccion',
            field=models.CharField(default='Dirección por defecto', max_length=255),
        ),
    ]
