# Generated by Django 5.0.7 on 2024-07-24 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chilestay', '0006_alter_inmueble_tipo_inmueble'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='capacidad_adultos',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='fecha_disponible_desde',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='fecha_disponible_hasta',
            field=models.DateField(blank=True, null=True),
        ),
    ]
